workflows:
  android-release:
    name: Pipisgram Android Build
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
      android_signing:
        - pipisgram_release_key
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk